name: Auto Organize LeetCode Solutions

on:
  push:
    paths:
      - "*.py"
      - "*.sql"
      - "*.cpp"
      - "*.r"
      - "*.ipynb"
      - "*.pbix"
      - "*.txt"
      - "*.md"

permissions:
  contents: write

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Move solution files to correct folders
        run: |
          mkdir -p Python SQL CPP R "AI-Tools" PowerBI

          for file in *.py; do
            [ -e "$file" ] || continue
            echo "### Problem Description + Solution" > "Python/$file"
            cat "$file" >> "Python/$file"
            git rm -f "$file"
          done

          for file in *.sql; do
            [ -e "$file" ] || continue
            echo "### Problem Description + Solution" > "SQL/$file"
            cat "$file" >> "SQL/$file"
            git rm -f "$file"
          done

          for file in *.cpp; do
            [ -e "$file" ] || continue
            echo "### Problem Description + Solution" > "CPP/$file"
            cat "$file" >> "CPP/$file"
            git rm -f "$file"
          done

          for file in *.r; do
            [ -e "$file" ] || continue
            echo "### Problem Description + Solution" > "R/$file"
            cat "$file" >> "R/$file"
            git rm -f "$file"
          done

          for file in *.ipynb; do
            [ -e "$file" ] || continue
            echo "### Notebook Problem + Solution" > "AI-Tools/$file"
            cat "$file" >> "AI-Tools/$file"
            git rm -f "$file"
          done

          for file in *.pbix; do
            [ -e "$file" ] || continue
            mv "$file" "PowerBI/$file"
            git rm -f "$file"
          done

      - name: Commit organized files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-move: Organized solutions by language" || echo "No changes to commit"
          git push
