name: Auto Move LeetCode Solutions

on:
  push:
    branches: [ master ]  # لو الفرع الافتراضي عندك اسمه main بدل master، استبدلها بـ main

permissions:
  contents: write

jobs:
  move_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Move Python and SQL files
        run: |
          mkdir -p Python
          mkdir -p SQL
          # انقل ملفات .py لأي مكان خارج Python/ (مع الحفاظ على الملفات الموجودة بالفعل)
          find . -type f -name "*.py" ! -path "./Python/*" -exec bash -c 'mv -n "$1" Python/' _ {} \;
          # انقل ملفات .sql لأي مكان خارج SQL/
          find . -type f -name "*.sql" ! -path "./SQL/*" -exec bash -c 'mv -n "$1" SQL/' _ {} \;

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto move Python and SQL files" || exit 0
          git push
