name: Auto Organize LeetHub Submissions

on:
  push:
    paths:
      - "*.py"
      - "*.sql"
      - "*.cpp"
      - "*.java"
      - "*.ipynb"
      - "*.r"
      - "*.jl"
      - "*.pbix"
      - "README.md"

jobs:
  organize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Move solutions to correct folders
        run: |
          # إنشاء المجلدات
          mkdir -p Python SQL CPP Java R Julia AI-Tools PowerBI

          for f in *.{py,sql,cpp,java,ipynb,r,jl,pbix}; do
            [ -e "$f" ] || continue

            problem=$(basename "$f" | cut -d. -f1)
            readme="README.md"

            case "$f" in
              *.py) out="Python/$f" ;;
              *.sql) out="SQL/$f" ;;
              *.cpp) out="CPP/$f" ;;
              *.java) out="Java/$f" ;;
              *.r) out="R/$f" ;;
              *.jl) out="Julia/$f" ;;
              *.ipynb) out="AI-Tools/$f" ;;
              *.pbix) out="PowerBI/$f" ;;
            esac

            # دمج الشرح + الحل داخل ملف واحد
            if [ -f "$readme" ]; then
              {
                echo '"""'
                cat "$readme"
                echo '"""'
                echo ""
                cat "$f"
              } > "$out"
            else
              cp "$f" "$out"
            fi

            # حذف النسخة اللي في الجذر
            rm "$f"
          done

      - name: Commit changes
        run: |
          git config --global user.name "LeetHub Bot"
          git config --global user.email "leetbot@example.com"
          git add .
          git commit -m "Auto-organized LeetHub submissions" || echo "No changes"
          git push
