name: Auto Organize LeetCode Solutions

on:
  push:
    paths:
      - "*.py"
      - "*.sql"
      - "*.cpp"
      - "*.r"
      - "*.ipynb"
      - "*.pbix"
      - "*.txt"
      - "*.md"

permissions:
  contents: write

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Move solution files to correct folders
        run: |
          mkdir -p Python SQL CPP R "AI-Tools" PowerBI

          # Function to merge problem description + solution
          merge_and_move() {
            file=$1
            folder=$2
            ext=$3
            base=$(basename "$file" ".$ext")
            readme="${base}.md"
            out="$folder/$file"

            echo ">>> Processing $file into $out"

            if [ -f "$readme" ]; then
              cat "$readme" > "$out"
              echo "" >> "$out"
              echo "```$ext" >> "$out"
              cat "$file" >> "$out"
              echo "```" >> "$out"
              git rm -f "$readme"
            else
              echo "### Problem Description Missing" > "$out"
              cat "$file" >> "$out"
            fi

            git rm -f "$file"
          }

          # Python
          for file in *.py; do
            [ -e "$file" ] || continue
            merge_and_move "$file" "Python" "py"
          done

          # SQL
          for file in *.sql; do
            [ -e "$file" ] || continue
            merge_and_move "$file" "SQL" "sql"
          done

          # CPP
          for file in *.cpp; do
            [ -e "$file" ] || continue
            merge_and_move "$file" "CPP" "cpp"
          done

          # R
          for file in *.r; do
            [ -e "$file" ] || continue
            merge_and_move "$file" "R" "r"
          done

          # AI Notebooks
          for file in *.ipynb; do
            [ -e "$file" ] || continue
            merge_and_move "$file" "AI-Tools" "ipynb"
          done

          # PowerBI files
          for file in *.pbix; do
            [ -e "$file" ] || continue
            mv "$file" "PowerBI/$file"
            git rm -f "$file"
          done

      - name: Commit organized files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-move: Organized solutions by language with descriptions" || echo "No changes to commit"
          git push
